### ISSUE TITLE
Build with scala 2.12.15 is failing, spark3.3.1, hadoop:3.3.4, hive:3.1..3

### ISSUE THREAD

**Issue by navneetpr** [apache/incubator-livy#380]
Exception when compiling 13 sources to /opt/incubator-livy/test-lib/target/classes
java.lang.NoSuchMethodError: scala.tools.nsc.Settings.nowarn()Lscala/tools/nsc/settings/AbsSettings$AbsSetting;

**Comment by cocdkl** [comment]
我也有这个问题，这边需要使用到pyspark 3.2.0之后的新功能pandas，希望能得到解决方案

**Comment by cocdkl** [comment]
官网上有问题的解决方案，这是地址https://issues.apache.org/jira/projects/LIVY/issues/LIVY-877?filter=allissues
具体方案是将scala-maven-plugin 插件升级到最新版本，我升级到的是4.8.1。
